spring.application.name=MySqlConnection
spring.datasource.username=root
spring.datasource.password=Thejas@ks123
spring.datasource.url=jdbc:mysql://localhost:3306/fullstackdevelopment
spring.jpa.hibernate.ddl-auto=update